export enum QUIZ_TYPE {
  QUIZ_GOAL = "QUIZ_GOAL",
  QUIZ_INTEREST = "QUIZ_INTEREST",
  QUIZ_BODY_TYPE = "QUIZ_BODY_TYPE",
  QUIZ_WEAK = "QUIZ_WEAK",
  QUIZ_HEIGHT_WEIGHT = "QUIZ_HEIGHT_WEIGHT",
  QUIZ_LEVEL = "QUIZ_LEVEL",
}
